# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x] # Check version of node

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install yarn
        run: npm install -g yarn@v1.22.10 # Check version of yarn, v2 uses --immutable
      - name: Install packages
        run: yarn install --frozen-lockfile # Check version of dependencies

      - name: Build app
        run: yarn build
        env:
          NEXT_PUBLIC_BASE_PATH: /nextjs-ghpages
      - name: Export app
        run: yarn export
        env:
          NEXT_PUBLIC_BASE_PATH: /nextjs-ghpages
      - run: touch ./out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7 # https://github.com/JamesIves/github-pages-deploy-action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
